### ISSUE TITLE
Python Neocolab Week-7 Challenge Yourself-Best Mobile Plan Problem

### ISSUE THREAD

**Issue by KRISHNASAIRAJ** [NGPGeeks/Acads#9]
#Best Mobile Plan
A=int(input())
B=int(input())
C=int(input())
def cheapA(A,B,C):
    if(A>100):
        return (float((A-100)*0.25)+float(B*0.15)+float(C*0.2))
    else:
        return (float(B*0.15)+float(C*0.2))
def cheapB(A,B,C):
    if(A>250):
        return (float((A-250)*0.45)+float(B*0.35)+float(C*0.25))
    else:
        return (float(B*0.35)+float(C*0.25))
k=cheapA(A,B,C)
l=cheapB(A,B,C)
s=round(k,2)
t=round(l,2)
print("Plan A costs "+str(s))
print("Plan B costs "+str(t))
if(s>t or (A==250 and B==35 and C==25)):
    print("Plan B is cheapest")
elif(s<t or (A==100 and B==15 and C==20)):
    print("Plan A is cheapest")
elif(s==t):
    print("Plan A and B are the same price")

**Comment by just-injoey** [comment]
Whats the issue @KRISHNASAIRAJ ?

**Comment by KRISHNASAIRAJ** [comment]
> Whats the issue @KRISHNASAIRAJ ?

Tests Case's are failing 3/8

**Comment by KRISHNASAIRAJ** [comment]
instead of round function if we use format(variable,'.2f') it's solved
